server_settings:
  host: 0.0.0.0
  port: 8080
  log_level: info
  ollama_enable: true
  ollama_cuda_visible_devices: none
  whisper_enable: true
  whisper_cuda_visible_devices: none
  pdf_parser_enable: true
  pdf_parser_cuda_visible_devices: none
  sensitive_words_enable: true
  sensitive_words_cuda_visible_devices: none
managed_workers:
- model_name: minicpm-v:8b
  model_path: cache
  backend: ollama
  task: generate
  ability: vision
  heartbeat_interval: 10
- model_name: bce-embedding-base_v1
  model_path: {{HOST_PATH}}/bussiness/embedding-models/bce-embedding-base_v1
  backend: sentence
  task: embedding
  ability: embedding
  port: 8002
  gpu_ids: []
  heartbeat_interval: 10
- model_name: bge-m3
  model_path: {{HOST_PATH}}/bussiness/embedding-models/bge-m3
  backend: sentence
  task: embedding
  ability: embedding
  port: 8003
  gpu_ids: []
  heartbeat_interval: 10
- model_name: Yuan-embedding-1.0
  model_path: {{HOST_PATH}}/bussiness/embedding-models/Yuan-embedding-1.0
  backend: sentence
  task: embedding
  ability: embedding
  port: 8004
  gpu_ids: []
  heartbeat_interval: 10
- model_name: bge-reranker-v2-m3
  model_path: {{HOST_PATH}}/bussiness/embedding-models/bge-reranker-v2-m3
  backend: sentence
  task: rerank
  ability: rerank
  port: 8005
  gpu_ids: []
  heartbeat_interval: 10
- model_name: gemma2:9b
  model_path: cache
  backend: ollama
  task: generate
  ability: chat
  heartbeat_interval: 10
